// ========== AUTH ==========
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const NEWPASSWORD_REQUEST = "NEWPASSWORD_REQUEST";
export const NEWPASSWORD_SUCCESS = "NEWPASSWORD_SUCCESS";
export const NEWPASSWORD_FAILURE = "NEWPASSWORD_FAILURE";

// ========== EQUIPMENT ==========
export const EQUIPMENT_CREATE_REQUEST = "EQUIPMENT_CREATE_REQUEST";
export const EQUIPMENT_CREATE_SUCCESS = "EQUIPMENT_CREATE_SUCCESS";
export const EQUIPMENT_CREATE_FAILURE = "EQUIPMENT_CREATE_FAILURE";

export const FETCH_EQUIPMENTS_REQUEST = "FETCH_EQUIPMENTS_REQUEST";
export const FETCH_EQUIPMENTS_SUCCESS = "FETCH_EQUIPMENTS_SUCCESS";
export const FETCH_EQUIPMENTS_FAILURE = "FETCH_EQUIPMENTS_FAILURE";
